### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HumzahChoudry**
It doesn't tell you to default to false until the last test.

### CODE REVIEW

**Comment by HumzahChoudry** [comment]
@DanielSeehausen

**Comment by HumzahChoudry** [comment]
@DanielSeehausen

**Comment by HumzahChoudry** [comment]
@DanielSeehausen

**Comment by DanielSeehausen** [comment]
@HumzahChoudry thank you! please make a PR for solution as well, making sure master and solution are up to date with the exception of the solution code itself . Easiest way to do this is to make a new branch off of solution and merge this branch into that one. You may get merge conflict hell. Once that is sorted out, just make sure rspec works and assign me to the pr! then I will bring both in.

**Pull request merged**
